### PR TITLE
Fixes for valac 0.34

### PR DESCRIPTION
**Pull request by astavale**
The Json.Serializable interface was corrected with this patch to Vala:
https://git.gnome.org/browse/vala/commit/?id=28fa5311c35522e9ade4b101fb4c81401d01f18a
This now makes building Valadate only possible with 0.34.0 when the fixes in this pull request are applied.

### CODE REVIEW

**Comment by chebizarro** [comment]
Given that this would break building for anyone not using 0.34 or higher, I would rather use preprocessor directives at a source level to determine the right method signatures. I'll try and work up a patch in the next day or so.

**Comment by chebizarro** [comment]
This has been addressed with  #e73dcc71acefdbd212b564d55a4818508c436181 which maintains backwards compatibility - thanks for the patch though!

**Comment by astavale** [comment]
Thanks for updating Valadate. 

If this comes up again it is worth noting that Vala does include build-in pre-processor defines for the Vala version - see https://wiki.gnome.org/Projects/Vala/Manual/Preprocessor

So the following code compiles and works fine without anything being added to the build system:

```
void main () {
    #if VALA_0_34
        print ("Compiled with Vala version 0.34+\n");
    #else
        print ("Compiled with Vala version before 0.34\n");
    #endif
}
```

There was some discussion a while ago of having a VALA_X_Y_Z define built in as well - see https://bugzilla.gnome.org/show_bug.cgi?id=712405

**Comment by chebizarro** [comment]
That was the solution I used in the end.

**Pull request closed without merging**
